name: 'build'
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add badge
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          badges: 'gh_license, gh_version, gh_stars'
          badge-style: 'flat-square'
